### ISSUE TITLE
Add `.npmignore`

### ISSUE THREAD

**Issue by rauchg** [zeit/arg#19]
I'm a huge fan of whitelists to make sure no garbage ever ends up in npm accidentally.
It would look approximately like this:

```
*
!index.js
!index.d.ts
```

**Comment by Qix-** [comment]
Why not use the files key in package.json to be explicit about what gets published instead of introducing another dotfile?

**Comment by Qix-** [comment]
Closing in favor of the `"files"` key as we already have that and it does exactly what you're suggesting.

Re-open if this is not the case or I'm misunderstanding something :)
