### ISSUE TITLE
Support defaults

### ISSUE THREAD

**Issue by matthewmueller** [zeit/arg#43]
It'd be sweet if this library also supported default arguments. The API could look like this:

```js
arg({
  '--help': Boolean,
  '-h': '--help',

  '--branch': String,
  '-b': '--branch',

  '--config': './config',
  '-c': '--config'
})
```

You could distinguish between `String` and a String argument with a default by doing:

```js
if (value === String) {
  // it's a string argument
}

if (typeof value === 'string') {
  // it's a string argument with a default
}
```

**Comment by rauchg** [comment]
Wouldn't destructuring defaults be a better option here? They don't work for `null`, but if we set `undefined` that could work

**Comment by rauchg** [comment]
If so, we should consider doing a major bump to get rid of `-` and `--` in the spec perhaps

**Comment by matthewmueller** [comment]
> Wouldn't destructuring defaults be a better option here?

How would this look? 

> If so, we should consider doing a major bump to get rid of - and -- in the spec perhaps

I quite like its explicitness but I do forget they're needed every time haha.

Another option could be supplying a function. I just noticed the `arg.flag(fn)` yet but it seems like that could be the solution.

**Comment by Qix-** [comment]
I'm :-1: on this. I think this is very clearly getting into scope creep territory.

**Comment by matthewmueller** [comment]
Sounds good. It's easy enough to do outside of this library.

**Comment by Qix-** [comment]
@matthewmueller Here's an example for a utility I am writing at the moment:

```javascript
const args = arg({
	'--help': Boolean,
	'-h': '--help',

	'--out-dir': String,
	'-o': '--out-dir',

	'--numeric-bold': Boolean,
	'-B': '--numeric-bold',

	'--bold': Number,
	'-b': '--bold',

	'--normal': Number,
	'-N': '--normal',

	'--path': String,
	'-p': '--path',

	'--out-name': String,
	'-O': '--out-name'
});

const {
	'--bold': boldWeight = 700,
	'--normal': normalWeight = 400,
	'--out-name': outputName = 'fonts'
} = args;
```

**Comment by matthewmueller** [comment]
Looks great, thanks for sharing! Destructuring, aliasing, and defaults in one call – JS is getting so crazy 😬

**Comment by rauschma** [comment]
@Qix- Suggestion: add this example to the project’s readme.
