### ISSUE TITLE
`arg` parses quoted argument values

### ISSUE THREAD

**Issue by raphaelyancey** [zeit/arg#44]
It seems like `arg` is parsing quoted strings.

Here is an online example: https://repl.it/repls/IllegalTraumaticLifecycles

Input string
```
--string "ES_JAVA_OPTS=-Xms512m -Xmx512m"
```

Output
```
Error: Unknown or unexpected option: -X
```

**Comment by Qix-** [comment]
Cannot reproduce.

```javascript
const arg = require('arg');

const args = arg({
	'--string': String
});

console.log(args['--string']);
```

Also, "quoted strings" have to do with your shell environment. We don't parse anything related to string handling, your shell simply passes in `ES_JAVA_OPTS=-Xms512m -Xmx512m` (without quotes) as a single `process.argv` element.

Please show reproduction code.

**Comment by raphaelyancey** [comment]
Issue is not in `arg` (discussion on https://github.com/raphaelyancey/cli2compose/issues/1). Thank you for your time.
