### ISSUE TITLE
Everything after "=" gets stripped off in long args with "=" in value

### ISSUE THREAD

**Issue by flexdinesh** [zeit/arg#47]
When an arg has `=` in the value, everything after (inc) `=` gets stripped off from the arg.

Pass this command to `arg()` —
```sh
yarn keystone dev --connect-to=mongodb://user:pass@localhost:27017/keystone?authSource=admin&w=1
```

**Current output**
`--connect-to` = `mongodb://user:pass@localhost:27017/keystone?authSource`

**Expected output**
`--connect-to` = `mongodb://user:pass@localhost:27017/keystone?authSource=admin&w=1`

This is essential for passing URLs as arg value.

**Comment by Qix-** [comment]
Fixed in `4.1.1`. Thanks for the report!
